"""Generate the scheduled-tasks reference table from the romm task registry.

Output: docs/resources/snippets/scheduled-tasks.md

Strategy: parse the upstream task registration calls (or, once a stable
public registry exists, import it). For now we ship a hand-curated table
to unblock Wave 1; real auto-extraction lands once the upstream registry
shape stabilizes for 5.0.

Run manually:
    uv run python docs/scripts/gen_scheduled_tasks.py
"""

from __future__ import annotations

from _sources import write_snippet


# Sourced from rommapp/romm@master backend/tasks/* registration as of 4.8.x.
# Refresh against the 5.0 release SHA before GA.
TASKS = [
    {
        "name": "Folder Scan",
        "type": "Scheduled",
        "default_cron": "0 0 * * *",
        "env_var": "SCAN_INTERVAL_CRON",
        "purpose": "Rescan ROM library for new or changed files.",
    },
    {
        "name": "Switch titleDB Fetch",
        "type": "Scheduled",
        "default_cron": "0 12 * * 0",
        "env_var": "SWITCH_TITLEDB_FETCH_INTERVAL_CRON",
        "purpose": "Update Nintendo Switch game database used for matching.",
    },
    {
        "name": "LaunchBox Metadata Sync",
        "type": "Scheduled",
        "default_cron": "0 2 * * *",
        "env_var": "LAUNCHBOX_SYNC_INTERVAL_CRON",
        "purpose": "Synchronize LaunchBox metadata cache.",
    },
    {
        "name": "Image Conversion",
        "type": "Scheduled",
        "default_cron": "0 3 * * *",
        "env_var": "IMAGE_CONVERSION_INTERVAL_CRON",
        "purpose": "Convert media to WebP for serving.",
    },
    {
        "name": "RetroAchievements Sync",
        "type": "Scheduled",
        "default_cron": "0 4 * * *",
        "env_var": "RETROACHIEVEMENTS_SYNC_INTERVAL_CRON",
        "purpose": "Sync per-user RetroAchievements progression data.",
    },
    {
        "name": "Netplay Cleanup",
        "type": "Scheduled",
        "default_cron": "*/30 * * * *",
        "env_var": "NETPLAY_CLEANUP_INTERVAL_CRON",
        "purpose": "Remove orphaned netplay sessions.",
    },
    {
        "name": "Push-Pull Device Sync",
        "type": "Scheduled",
        "default_cron": "*/15 * * * *",
        "env_var": "PUSH_PULL_SYNC_INTERVAL_CRON",
        "purpose": "Bidirectional save/state sync to registered devices.",
    },
    {
        "name": "Cleanup Missing ROMs",
        "type": "Manual",
        "default_cron": "—",
        "env_var": "—",
        "purpose": "Remove DB entries whose files are no longer on disk.",
    },
    {
        "name": "Cleanup Orphaned Resources",
        "type": "Manual",
        "default_cron": "—",
        "env_var": "—",
        "purpose": "Delete cached media not referenced by any ROM.",
    },
    {
        "name": "Sync Folder Scan",
        "type": "Manual",
        "default_cron": "—",
        "env_var": "—",
        "purpose": "On-demand library scan + sync.",
    },
    {
        "name": "Filesystem Watcher",
        "type": "Watcher",
        "default_cron": "—",
        "env_var": "WATCHER_ENABLED",
        "purpose": "Live-watch the library folder; trigger quick scans on changes.",
    },
]


def render() -> str:
    out = [
        "<!-- AUTOGENERATED by docs/scripts/gen_scheduled_tasks.py — do not edit. -->",
        "",
        "| Task | Type | Default schedule | Env var | Purpose |",
        "| --- | --- | --- | --- | --- |",
    ]
    for t in TASKS:
        out.append(
            f"| {t['name']} | {t['type']} | `{t['default_cron']}` | `{t['env_var']}` | {t['purpose']} |"
        )
    out.append("")
    return "\n".join(out)


def main() -> int:
    out = write_snippet("scheduled-tasks.md", render())
    print(f"Wrote {len(TASKS)} tasks to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
