"""Generate the supported-platforms table from rommapp/romm.

Output: docs/resources/snippets/supported-platforms.md

Strategy: fetch backend/utils/generate_supported_platforms.py from upstream
along with the platform metadata it consumes, then exec it in a sandbox.
For now this is a stub that emits a placeholder snippet. The real exec
needs a copy of the upstream utility's input data layout, which we'll wire
up after pinning a 5.0 SHA in sources.toml.

Run manually:
    uv run python docs/scripts/gen_platforms.py
"""

from __future__ import annotations

from _sources import write_snippet


PLACEHOLDER = """\
<!-- AUTOGENERATED by docs/scripts/gen_platforms.py: do not edit. -->
<!-- TODO: wire to romm/backend/utils/generate_supported_platforms.py once
     a 5.0 SHA is pinned in sources.toml. -->

_Supported-platforms table is generated at build time. Run
`uv run python docs/scripts/gen_platforms.py` to refresh._
"""


def main() -> int:
    out = write_snippet("supported-platforms.md", PLACEHOLDER)
    print(f"Wrote placeholder to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
