"""Generate the env-vars reference table from rommapp/romm's env.template.

Output: docs/resources/snippets/env-vars.md (a Markdown table).

Included by reference/environment-variables.md via:
    --8<-- "env-vars.md"

Run manually:
    uv run python docs/scripts/gen_env_vars.py
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from typing import Iterable

from _sources import fetch_text, romm_raw_url, write_snippet

SECTION_RE = re.compile(r"^#\s*([A-Z][A-Z0-9 _/\-&]+?)\s*#*\s*$")
COMMENT_RE = re.compile(r"^#\s?(.*)$")
ASSIGN_RE = re.compile(r"^([A-Z][A-Z0-9_]*)=(.*)$")


def parse(env_template: str) -> list[dict]:
    section = "General"
    pending_comments: list[str] = []
    rows: list[dict] = []

    for raw in env_template.splitlines():
        line = raw.rstrip()
        if not line.strip():
            pending_comments = []
            continue

        sec = SECTION_RE.match(line)
        if sec and len(line) > 4 and line.startswith("#") and "=" not in line:
            section = sec.group(1).strip().title()
            pending_comments = []
            continue

        cmt = COMMENT_RE.match(line)
        if cmt:
            pending_comments.append(cmt.group(1).strip())
            continue

        m = ASSIGN_RE.match(line)
        if m:
            name, default = m.group(1), m.group(2).strip()
            rows.append({
                "section": section,
                "name": name,
                "default": default,
                "description": " ".join(c for c in pending_comments if c),
            })
            pending_comments = []

    return rows


def render(rows: Iterable[dict]) -> str:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        grouped[r["section"]].append(r)

    out: list[str] = []
    out.append("<!-- AUTOGENERATED by docs/scripts/gen_env_vars.py — do not edit. -->")
    out.append("")
    for section, items in grouped.items():
        out.append(f"### {section}")
        out.append("")
        out.append("| Variable | Default | Description |")
        out.append("| --- | --- | --- |")
        for r in items:
            default = r["default"] if r["default"] else "_(unset)_"
            desc = r["description"] or "—"
            out.append(f"| `{r['name']}` | `{default}` | {desc} |")
        out.append("")
    return "\n".join(out)


def main() -> int:
    url = romm_raw_url("env.template")
    text = fetch_text(url)
    rows = parse(text)
    if not rows:
        print(f"WARN: no env vars parsed from {url}", file=sys.stderr)
        return 1
    snippet = render(rows)
    out = write_snippet("env-vars.md", snippet)
    print(f"Wrote {len(rows)} env vars to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
