"""Generate the supported-platforms table from a local rommapp/romm checkout.

Output: docs/resources/snippets/supported-platforms.md

Strategy: shell out to the upstream generator at
`backend/utils/generate_supported_platforms.py`. That module imports the
full romm handler stack (redis, db, httpx), so it has to run inside
romm's own uv environment, not this one.

Set `ROMM_SRC` to the romm checkout root (read from .env at the repo root
or from the process environment).

Run manually:
    uv run python -m scripts.gen_platforms
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from dotenv import load_dotenv

from scripts._sources import ENV_FILE, write_snippet

HEADER = "<!-- AUTOGENERATED by scripts/gen_platforms.py: do not edit. -->\n"

load_dotenv(ENV_FILE)


def main() -> int:
    romm_src = os.environ.get("ROMM_SRC")
    if not romm_src:
        print(
            f"ROMM_SRC not set (add it to {ENV_FILE} or the environment)",
            file=sys.stderr,
        )
        return 1

    backend = Path(romm_src).expanduser() / "backend"
    script = backend / "utils" / "generate_supported_platforms.py"
    if not script.exists():
        print(f"error: {script} not found (ROMM_SRC={romm_src})", file=sys.stderr)
        return 1

    result = subprocess.run(
        ["uv", "run", "python", "-m", "utils.generate_supported_platforms"],
        cwd=backend,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        return result.returncode

    lines = result.stdout.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.startswith("|Platform"))
    except StopIteration:
        print("error: could not find table header in upstream output", file=sys.stderr)
        return 1

    table = "\n".join(lines[start:]) + "\n"
    rows = sum(1 for line in lines[start:] if line.startswith("| "))
    out = write_snippet("supported-platforms.md", HEADER + "\n" + table)
    print(f"Wrote {rows} platforms to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
