"""Generate the platform folder-alias table from rommapp/romm.

Output: docs/resources/snippets/platform-aliases.md (a Markdown table).

Included by platforms/supported-platforms.md via:
    --8<-- "platform-aliases.md"

Sources, both fetched from the ref pinned in sources.toml:
- backend/utils/platform_aliases.py for the PLATFORM_FS_ALIASES dict
- backend/utils/platform_slugs.py for the UniversalPlatformSlug values

Both are parsed with `ast` rather than imported, so this needs no romm
checkout and no romm environment (unlike gen_platforms, which shells out to
romm's own generator because that one imports the handler stack).

Folder names that share a target are grouped onto one row, so the rows that
collapse several folders onto one platform read as such.

Run manually:
    uv run python -m scripts.gen_platform_aliases

A ref without an alias table leaves the committed snippet untouched and
warns, rather than failing, so it never sinks a release bump that the other
generators would have completed.

Pass --ref to read a ref that is not pinned yet, which is how the table is
seeded before the release that first carries the alias table:
    uv run python -m scripts.gen_platform_aliases --ref master
"""

from __future__ import annotations

import argparse
import ast
import sys
import urllib.error

from scripts._sources import fetch_text, load_sources, write_snippet

HEADER = "<!-- AUTOGENERATED by scripts/gen_platform_aliases.py: do not edit. -->\n"

SNIPPET = "platform-aliases.md"

ALIASES_PATH = "backend/utils/platform_aliases.py"
SLUGS_PATH = "backend/utils/platform_slugs.py"

ALIASES_NAME = "PLATFORM_FS_ALIASES"
SLUGS_CLASS = "UniversalPlatformSlug"


def raw_url(ref: str, path: str) -> str:
    repo = load_sources()["romm"]["repo"]
    return f"https://raw.githubusercontent.com/{repo}/{ref}/{path}"


def parse_slug_values(source: str) -> dict[str, str]:
    """Map UniversalPlatformSlug member names to their string values."""
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == SLUGS_CLASS:
            return {
                target.id: stmt.value.value
                for stmt in node.body
                if isinstance(stmt, ast.Assign)
                and isinstance(stmt.value, ast.Constant)
                and isinstance(stmt.value.value, str)
                for target in stmt.targets
                if isinstance(target, ast.Name)
            }
    raise ValueError(f"{SLUGS_CLASS} not found in {SLUGS_PATH}")


def parse_aliases(source: str) -> dict[str, str]:
    """Map folder names to the slug member name each resolves to."""
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        if not any(
            isinstance(t, ast.Name) and t.id == ALIASES_NAME for t in targets
        ):
            continue
        if not isinstance(node.value, ast.Dict):
            raise ValueError(f"{ALIASES_NAME} is not a dict literal")
        return {
            key.value: value.attr
            for key, value in zip(node.value.keys, node.value.values)
            if isinstance(key, ast.Constant)
            and isinstance(key.value, str)
            and isinstance(value, ast.Attribute)
        }
    raise ValueError(f"{ALIASES_NAME} not found in {ALIASES_PATH}")


def build_table(folders: dict[str, str], slug_values: dict[str, str]) -> str:
    """Render one row per target slug, listing every folder that reaches it."""
    by_slug: dict[str, list[str]] = {}
    for folder, member in sorted(folders.items()):
        try:
            slug = slug_values[member]
        except KeyError:
            raise ValueError(
                f"{ALIASES_NAME} maps {folder!r} to {SLUGS_CLASS}.{member}, "
                f"which {SLUGS_PATH} does not define"
            ) from None
        by_slug.setdefault(slug, []).append(folder)

    lines = ["| Folder name | Platform slug |", "| --- | --- |"]
    for slug in sorted(by_slug):
        names = ", ".join(f"`{folder}`" for folder in by_slug[slug])
        lines.append(f"| {names} | `{slug}` |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--ref",
        help="Ref to read instead of the one pinned in sources.toml.",
    )
    args = parser.parse_args()

    ref = args.ref or load_sources()["romm"]["ref"]

    sources = {}
    for path in (ALIASES_PATH, SLUGS_PATH):
        try:
            sources[path] = fetch_text(raw_url(ref, path))
        except urllib.error.HTTPError as exc:
            if exc.code == 404:
                # Leave the committed table alone rather than failing. This runs
                # in the release bump alongside the other generators, and a ref
                # without an alias table should cost the alias table, not the
                # whole bump PR.
                print(
                    f"warning: {path} does not exist at ref {ref}, so "
                    f"{SNIPPET} is unchanged. The alias table landed after "
                    "5.2.0, so a ref predating the release that carries it "
                    "has nothing to generate from.",
                    file=sys.stderr,
                )
                return 0
            raise

    folders = parse_aliases(sources[ALIASES_PATH])
    slug_values = parse_slug_values(sources[SLUGS_PATH])
    table = build_table(folders, slug_values)

    out = write_snippet(SNIPPET, HEADER + "\n" + table)
    platforms = table.count("\n") - 2
    print(f"Wrote {len(folders)} folder names over {platforms} platforms to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
