"""Generate the scheduled-tasks reference table from the romm task registry.

Parse the upstream task registration calls (or, once a stable
public registry exists, import it), and generate 
docs/resources/snippets/scheduled-tasks.md

Run manually:
    uv run python -m scripts.gen_scheduled_tasks
"""

from __future__ import annotations

from scripts._sources import write_snippet


# Sourced from rommapp/romm backend/tasks/ at the ref pinned in sources.toml.
# Task titles, `enabled=` flags and `cron_string=` defaults come from each
# task's constructor; env var names are cross-checked against env.template.
TASKS = [
    {
        "name": "Scheduled rescan",
        "type": "Scheduled",
        "default_cron": "0 3 * * *",
        "enable_var": "ENABLE_SCHEDULED_RESCAN",
        "env_var": "SCHEDULED_RESCAN_CRON",
        "purpose": "Rescan the entire ROM library for new or changed files.",
    },
    {
        "name": "Switch TitleDB update",
        "type": "Scheduled",
        "default_cron": "0 4 * * *",
        "enable_var": "ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB",
        "env_var": "SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON",
        "purpose": "Update the Nintendo Switch TitleDB index used for matching.",
    },
    {
        "name": "LaunchBox metadata update",
        "type": "Scheduled",
        "default_cron": "0 4 * * *",
        "enable_var": "ENABLE_SCHEDULED_UPDATE_LAUNCHBOX_METADATA",
        "env_var": "SCHEDULED_UPDATE_LAUNCHBOX_METADATA_CRON",
        "purpose": "Refresh the LaunchBox metadata store.",
    },
    {
        "name": "Convert images to WebP",
        "type": "Scheduled",
        "default_cron": "0 4 * * *",
        "enable_var": "ENABLE_SCHEDULED_CONVERT_IMAGES_TO_WEBP",
        "env_var": "SCHEDULED_CONVERT_IMAGES_TO_WEBP_CRON",
        "purpose": "Convert existing PNG, JPG, BMP, TIFF and GIF media to WebP.",
    },
    {
        "name": "Cleanup orphaned resources",
        "type": "Scheduled",
        "default_cron": "0 5 * * *",
        "enable_var": "ENABLE_SCHEDULED_CLEANUP_ORPHANED_RESOURCES",
        "env_var": "SCHEDULED_CLEANUP_ORPHANED_RESOURCES_CRON",
        "purpose": "Delete covers, screenshots and other resources left behind by deleted ROMs.",
    },
    {
        "name": "RetroAchievements progress sync",
        "type": "Scheduled",
        "default_cron": "0 4 * * *",
        "enable_var": "ENABLE_SCHEDULED_RETROACHIEVEMENTS_PROGRESS_SYNC",
        "env_var": "SCHEDULED_RETROACHIEVEMENTS_PROGRESS_SYNC_CRON",
        "purpose": "Update RetroAchievements progress for all users.",
    },
    {
        "name": "Push-pull device sync",
        "type": "Scheduled",
        "default_cron": "*/30 * * * *",
        "enable_var": "ENABLE_SYNC_PUSH_PULL",
        "env_var": "SYNC_PUSH_PULL_CRON",
        "purpose": "Sync saves with registered devices over SSH/SFTP.",
    },
    {
        "name": "Netplay cleanup",
        "type": "Scheduled",
        "default_cron": "*/30 * * * *",
        "enable_var": "-",
        "env_var": "-",
        "purpose": "Clean up empty netplay rooms. Always on, not configurable.",
    },
    {
        "name": "Upload tmp cleanup",
        "type": "Scheduled",
        "default_cron": "0 * * * *",
        "enable_var": "-",
        "env_var": "-",
        "purpose": "Remove orphaned chunked-upload temp directories. Always on, not configurable.",
    },
    {
        "name": "ZIP cache cleanup",
        "type": "Scheduled",
        "default_cron": "0 4 * * *",
        "enable_var": "-",
        "env_var": "-",
        "purpose": "Remove stale cached ZIP files on a tiered TTL. Always on, not configurable.",
    },
    {
        "name": "Cleanup missing ROMs",
        "type": "Manual",
        "default_cron": "-",
        "enable_var": "-",
        "env_var": "-",
        "purpose": "Delete database entries for ROMs flagged as missing from the filesystem.",
    },
    {
        "name": "Recompute save content hashes",
        "type": "Manual",
        "default_cron": "-",
        "enable_var": "-",
        "env_var": "-",
        "purpose": "Recompute content hashes for stored saves.",
    },
    {
        "name": "Sync folder scan",
        "type": "Manual",
        "default_cron": "-",
        "enable_var": "-",
        "env_var": "-",
        "purpose": "Scan device sync folders for new save files.",
    },
    {
        "name": "Filesystem watcher",
        "type": "Watcher",
        "default_cron": "-",
        "enable_var": "ENABLE_RESCAN_ON_FILESYSTEM_CHANGE",
        "env_var": "RESCAN_ON_FILESYSTEM_CHANGE_DELAY",
        "purpose": "Watch the library folder and trigger a rescan on changes.",
    },
    {
        "name": "Sync folder watcher",
        "type": "Watcher",
        "default_cron": "-",
        "enable_var": "ENABLE_SYNC_FOLDER_WATCHER",
        "env_var": "SYNC_FOLDER_SCAN_DELAY",
        "purpose": "Watch the sync folder and trigger a scan on changes.",
    },
]


def render() -> str:
    out = [
        "<!-- AUTOGENERATED by scripts/gen_scheduled_tasks.py: do not edit. -->",
        "",
        "| Task | Type | Default schedule | Enable var | Schedule/delay var | Purpose |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for t in TASKS:
        out.append(
            f"| {t['name']} | {t['type']} | `{t['default_cron']}` "
            f"| `{t['enable_var']}` | `{t['env_var']}` | {t['purpose']} |"
        )
    out.append("")
    return "\n".join(out)


def main() -> int:
    out = write_snippet("scheduled-tasks.md", render())
    print(f"Wrote {len(TASKS)} tasks to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
