"""Generate the env-vars reference table from rommapp/romm's env.template.

Output: docs/resources/snippets/env-vars.md (a Markdown table).

Included by reference/environment-variables.md via:
    --8<-- "env-vars.md"

Run manually:
    uv run python -m scripts.gen_env_vars

The env.template format this parses:

    # Section Name
    VAR_NAME=default_value  # Description
    VAR_WITH_REQUIRED=  # Description [REQUIRED]
    VAR_QUOTED="value with spaces"  # Description

Rules:
- Lines starting with `#` and no `=` are section headers.
- Variable lines are `KEY=VALUE  # COMMENT` with two-or-more spaces
  before the `#` that introduces the inline comment.
- `[REQUIRED]` anywhere in the comment flags the variable as required.
- Surrounding double quotes on the default value are stripped.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from typing import Iterable

from scripts._sources import fetch_text, romm_raw_url, write_snippet

# KEY=VALUE, followed optionally by `  # comment`. Value may contain spaces.
VAR_LINE_RE = re.compile(r"^([A-Z][A-Z0-9_]*)=(.*)$")
# The inline-comment separator: 2+ spaces, then `#`, then optional space.
INLINE_COMMENT_RE = re.compile(r"\s{2,}#\s*(.*)$")


def parse_var(line: str) -> dict | None:
    m = VAR_LINE_RE.match(line)
    if not m:
        return None

    name = m.group(1)
    rest = m.group(2)

    comment_match = INLINE_COMMENT_RE.search(rest)
    if comment_match:
        comment = comment_match.group(1).strip()
        value = rest[: comment_match.start()]
    else:
        comment = ""
        value = rest

    value = value.strip()
    # Strip surrounding double quotes from the default value.
    if len(value) >= 2 and value.startswith('"') and value.endswith('"'):
        value = value[1:-1]

    required = "[REQUIRED]" in comment
    description = comment.replace("[REQUIRED]", "").strip()

    return {
        "name": name,
        "default": value,
        "description": description,
        "required": required,
    }


def parse(env_template: str) -> list[dict]:
    section = "General"
    rows: list[dict] = []

    for raw in env_template.splitlines():
        line = raw.rstrip()
        if not line.strip():
            continue

        # Variable line: has `=` and starts with an uppercase letter.
        if "=" in line and line[:1].isalpha() and line[:1].isupper():
            row = parse_var(line)
            if row:
                row["section"] = section
                rows.append(row)
                continue

        # Section header: comment line with no `=`.
        if line.startswith("#"):
            text = line.lstrip("#").strip()
            if text and "=" not in text:
                section = text

    return rows


def render(rows: Iterable[dict]) -> str:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        grouped[r["section"]].append(r)

    out: list[str] = []
    out.append("<!-- AUTOGENERATED by scripts/gen_env_vars.py: do not edit. -->")
    out.append("")

    for section, items in grouped.items():
        out.append(f"### {section}")
        out.append("")
        out.append("| Variable | Default | Required | Description |")
        out.append("| --- | --- | :---: | --- |")
        for r in items:
            default = f"`{r['default']}`" if r["default"] else ""
            required = "`✓`" if r["required"] else ""
            desc = r["description"] or "-"
            out.append(
                f"| `{r['name']}` | {default} | {required} | {desc} |"
            )
        out.append("")

    return "\n".join(out)


def main() -> int:
    url = romm_raw_url("env.template")
    text = fetch_text(url)
    rows = parse(text)
    if not rows:
        print(f"WARN: no env vars parsed from {url}", file=sys.stderr)
        return 1
    snippet = render(rows)
    out = write_snippet("env-vars.md", snippet)
    required = sum(1 for r in rows if r["required"])
    print(f"Wrote {len(rows)} env vars ({required} required) to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
